name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Make secrets
      env:
        USERNAME: ${{ secrets.DB_USERNAME}}
        PASSWORD: ${{ secrets.DB_PASSWORD}}
        DATABASE: ${{ secrets.DB_DATABASE}}
      run: mkdir config
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Build image
      run: docker build dockerfile . -t ${{ secrets.DOCKERHUB_USERNAME }}/growth-be:latest
