name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: Setting
    runs-on: unbuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2
