name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Make secrets
      env:
        USERNAME: ${{ secrets.DB_USERNAME}}
        PASSWORD: ${{ secrets.DB_PASSWORD}}
        DATABASE: ${{ secrets.DB_DATABASE}}
      run: mkdir config
